INSERT INTO `crm_pernexium`.`contact_status` (`name`) VALUES ('Contacto');
INSERT INTO `crm_pernexium`.`contact_status` (`name`) VALUES ('No Contacto');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Pago Parcial');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Promesa de Pago');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Cliente no Define');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Seguimiento a PP');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Pago Efectuado');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Cuenta Liquidada');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Mensaje con Terceros');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Mensaje con Familiar');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Defunción');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Aclaración');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Cuenta Corriente');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Negativa de Pago');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('1', 'Llamar Después');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('2', 'Buzón de Voz');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('2', 'Ilocalizable');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('2', 'No Contesta');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('2', 'Cuelga Llamada');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('2', 'Fuera de Servicio');
INSERT INTO `crm_pernexium`.`contact_status` (`parent_contact_status_id`, `name`) VALUES ('2', 'Teléfono Equivocado');
